### ISSUE TITLE
Fix wrong aspect ratio in svg

### ISSUE THREAD

**Issue by SpaceK33z** [Volst/ether-dream-tools#27]
![screen shot 2018-10-09 at 21 56 57](https://user-images.githubusercontent.com/533616/46694883-412ee180-cc0e-11e8-8286-1d662647ad62.png)

The above happens when I use our Volst logo svg. It's barely visible on the screenshot but it takes up the full canvas. Can you fix it so it respects the aspect ratio?

**Comment by Rutger** [comment]
Could you maybe make a new example file for the SVG Volst logo?
