### ISSUE TITLE
Fix analog modulation support

### ISSUE THREAD

**Issue by Rutger** [Volst/ether-dream-tools#41]
In the tests we did with your new laser, analog modulation didn't seem to work correctly. Even though the laser had support for this feature, color transitions were quite harsh. Please look into if its a setting or if it's an error in the etherdream tools.

**Comment by SpaceK33z** [comment]
In other modes of the laser it also has this harsh color transition. Which is kinda weird... I don't think it's a setting.

I'll load up an ILDA file with the SD card reader and see if it happens there also.

**Comment by SpaceK33z** [comment]
- The ILDA files my laser comes with have hardcoded "harsh" color transitions
- Ether Dream itself should [support analogue modulation](https://photonlexicon.com/forums/showthread.php/19279-recommendations-for-dac).

**Comment by SpaceK33z** [comment]
Fixed, it was just a bug in our private projects code.
